//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee1
    {
        public int id { get; set; }
        public string fastname { get; set; }
        public string lastname { get; set; }
        public string gender { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> deparmentid { get; set; }
    
        public virtual Department1 Department1 { get; set; }
    }
}
